### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by ZucchiniZe** [jimeh/docker-znc#12]
Does this support ssl out of the box or do I have to screw around with it?

**Comment by jimeh** [comment]
I haven't looked into using SSL at all, so you'd most likely have to mess around with it for the time being.

**Comment by lorn** [comment]
I'm using SSL and I didn't have any problem.

**Comment by jimeh** [comment]
@lorn That's a nice surprise, thanks :)... @ZucchiniZe I guess that answers your question :)
